echo "                                                                                                      "
echo "                                                                                                      "
echo "        CCCCCCCCCCCCCUUUUUUUU     UUUUUUUUBBBBBBBBBBBBBBBBB    333333333333333   DDDDDDDDDDDDD        "
echo "     CCC::::::::::::CU::::::U     U::::::UB::::::::::::::::B  3:::::::::::::::33 D::::::::::::DDD     "
echo "   CC:::::::::::::::CU::::::U     U::::::UB::::::BBBBBB:::::B 3::::::33333::::::3D:::::::::::::::DD   "
echo "  C:::::CCCCCCCC::::CUU:::::U     U:::::UUBB:::::B     B:::::B3333333     3:::::3DDD:::::DDDDD:::::D  "
echo " C:::::C       CCCCCC U:::::U     U:::::U   B::::B     B:::::B            3:::::3  D:::::D    D:::::D "
echo "C:::::C               U:::::D     D:::::U   B::::B     B:::::B            3:::::3  D:::::D     D:::::D"
echo "C:::::C               U:::::D     D:::::U   B::::BBBBBB:::::B     33333333:::::3   D:::::D     D:::::D"
echo "C:::::C               U:::::D     D:::::U   B:::::::::::::BB      3:::::::::::3    D:::::D     D:::::D"
echo "C:::::C               U:::::D     D:::::U   B::::BBBBBB:::::B     33333333:::::3   D:::::D     D:::::D"
echo "C:::::C               U:::::D     D:::::U   B::::B     B:::::B            3:::::3  D:::::D     D:::::D"
echo "C:::::C               U:::::D     D:::::U   B::::B     B:::::B            3:::::3  D:::::D     D:::::D"
echo " C:::::C       CCCCCC U::::::U   U::::::U   B::::B     B:::::B            3:::::3  D:::::D    D:::::D "
echo "  C:::::CCCCCCCC::::C U:::::::UUU:::::::U BB:::::BBBBBB::::::B3333333     3:::::3DDD:::::DDDDD:::::D  "
echo "   CC:::::::::::::::C  UU:::::::::::::UU  B:::::::::::::::::B 3::::::33333::::::3D:::::::::::::::DD   "
echo "     CCC::::::::::::C    UU:::::::::UU    B::::::::::::::::B  3:::::::::::::::33 D::::::::::::DDD     "
echo "        CCCCCCCCCCCCC      UUUUUUUUU      BBBBBBBBBBBBBBBBB    333333333333333   DDDDDDDDDDDDD        "
echo "                                                                                                      "